export const messages = {
  en: {
    language: { label: 'Language', english: 'English', hindi: 'हिंदी' },
    navigation: {
      primary: 'Primary navigation', account: 'Account navigation', findDoctors: 'Find Doctors', myAppointments: 'My Appointments', appointments: 'Appointments', notifications: 'Notifications',
      login: 'Login', register: 'Register', logout: 'Logout', wait: 'Wait…', greeting: 'Hi,', checkingSession: 'Checking sign-in status',
      notificationCount: 'Notifications, {{count}} unread', logoutFailed: 'Logout failed. Please try again.',
    },
    common: { tryAgain: 'Try again', home: 'Home', medreachHome: 'MedReach home', patientConsultationActions: 'Patient consultation actions', doctors: 'Doctors', close: 'Close', previous: 'Previous', next: 'Next' },
    footer: { patients: 'Patients', forDoctors: 'For doctors', howItWorks: 'How it works', doctorLogin: 'Doctor login', verification: 'Verification', about: 'About', privacy: 'Privacy', terms: 'Terms', description: 'Remote healthcare that helps patients find verified doctors and continue care with confidence.', findDoctor: 'Find a doctor', rights: '© 2026 MedReach. All rights reserved.', emergency: 'MedReach is for non-emergency healthcare only. Contact local emergency services for urgent help.', label: 'Footer' },
    search: { label: 'Search doctors', placeholder: 'Search doctors, specializations, or health concerns', submit: 'Find doctors' },
    home: {
      heroEyebrow: 'REMOTE CARE, MADE CLEARER', heroTitle: 'Care that continues, wherever you are.', heroCopy: 'Find verified doctors, view real availability, book remote consultations and keep follow-up care connected.', heroAlt: 'A doctor providing remote care from her consultation room', emergency: 'Not for emergencies. If you need urgent help, contact your local emergency service.',
      browse: 'Browse care', browseTitle: 'Start with the care you need.', browseCopy: 'Choose a starting point and meet doctors with the right focus for your concern.', viewAll: 'View all doctors', loadingSpecializations: 'Loading specializations', specializationError: 'Live specialization data is temporarily unavailable. You can still browse by care area.',
      journey: 'Your care journey', journeyTitle: 'Clear from search to follow-up.', journeyCopy: 'A simple path to remote care, with the context from each step ready for the next one.', stepSearch: 'Search', stepSearchCopy: 'Search by doctor, specialization or health concern.', stepChoose: 'Choose', stepChooseCopy: 'Choose real availability and a 30-minute slot.', stepMeet: 'Meet', stepMeetCopy: 'Meet the doctor remotely.', stepContinue: 'Continue', stepContinueCopy: 'Keep consultations, prescriptions and follow-ups connected.',
      continuity: 'Continuity matters', continuityTitle: 'Care shouldn’t restart with every appointment.', continuityCopy: 'MedReach keeps consultations, follow-ups and the context around your care connected, so the next conversation can begin where the last one ended.', createAccount: 'Create your account', continuityAlt: 'A patient reviewing her follow-up care plan at home',
      discovery: 'Doctor discovery', discoveryTitle: 'Know who you’re consulting before you book.', discoveryCopy: 'Review verified profiles, qualifications and professional information, explore each doctor’s specialization, then choose real availability and a clear path to remote care.', discoveryAlt: 'A doctor speaking attentively during a remote consultation',
      beyond: 'Beyond the consultation', beyondTitle: 'More of your healthcare, connected.', beyondCopy: 'A considered look at where MedReach is headed—from prescription-connected medicine access to useful guidance from verified doctors.', medicines: 'MEDICINES', medicinesTitle: 'Prescription-connected access, without losing the care context.', medicinesCopy: 'Designed to make prescribed medicines easier to understand, organize and follow within the wider care journey.', medicinesAlt: 'Prescription medicines arranged with a care instruction sheet', doctorInsights: 'DOCTOR INSIGHTS', insightsTitle: 'Guidance from verified doctors.', insightsCopy: 'Educational perspectives grounded in clinical experience, presented with clarity.', insightsAlt: 'A doctor reviewing educational healthcare material', meetDoctors: 'Meet our doctors', healthArticles: 'HEALTH ARTICLES', articlesTitle: 'Useful reading for better-informed care.', articlesCopy: 'A considered home for clear, plain-language health education as MedReach grows.',
      trust: 'Trust at every step', trustTitle: 'Built for care that feels considered.', trustOne: 'Professional review', trustOneCopy: 'Registration information is reviewed before approved doctor profiles are made public.', trustTwo: 'Permission-led privacy', trustTwoCopy: 'Protected health information is controlled by permissions throughout the care experience.', trustThree: 'One connected journey', trustThreeCopy: 'Appointments, consultations and follow-ups remain part of one continuous-care journey.',
    },
    specializations: { 'General Medicine': 'General Medicine', Dermatology: 'Dermatology', Cardiology: 'Cardiology', Gynecology: 'Gynecology', Pediatrics: 'Pediatrics', Psychiatry: 'Psychiatry' },
    filters: { label: 'Doctor filters', specialization: 'Specialization', specializationFilter: 'Specialization filter', allSpecializations: 'All specializations', availability: 'Availability filter', fee: 'Fee', feeFilter: 'Fee filter', experience: 'Experience', experienceFilter: 'Experience filter', all: 'Filters', clearAll: 'Clear all', refine: 'Refine search', allFilters: 'All filters', close: 'Close all filters', availableOn: 'Available on', consultationFee: 'Consultation fee', anyFee: 'Any fee', upTo: 'Up to ₹{{amount}}', anyExperience: 'Any experience', yearsPlus: '{{years}}+ years', reset: 'Reset filters', showResults: 'Show results' },
    calendar: { anyDate: 'Any date', chooseDate: 'Choose availability date', previousMonth: 'Previous month', nextMonth: 'Next month', clear: 'Clear', today: 'Today', weekdays: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'] },
    results: { breadcrumb: 'Breadcrumb', findCare: 'Find care', title: 'Find a doctor', copy: 'Search verified doctors by specialization, professional details and real availability.', specializationError: 'Specialization options are temporarily unavailable.', finding: 'Finding doctors…', oneFound: '{{count}} doctor found', manyFound: '{{count}} doctors found', forQuery: 'Results for', sort: 'Sort:', earliest: 'Earliest availability first', loadError: 'We couldn’t load doctors', noMatch: 'No doctors match these filters', noMatchCopy: 'Try changing your search or filters.', clearFilters: 'Clear filters', pagination: 'Doctor results pagination', page: 'Page {{page}} of {{pages}}' },
    doctorCard: { portrait: 'Portrait of {{name}}', verified: 'Verified doctor', yearsExperience: '{{years}} years experience', selectedDate: 'Selected date', nextAvailable: 'Next available', available: 'Available {{date}}', noSlots: 'No upcoming slots', consultationFee: 'Consultation fee', viewProfile: 'View profile' },
    profile: { notFound: 'Doctor profile not found', loadError: 'We couldn’t load this profile', unavailable: 'This doctor is unavailable or the profile is no longer public.', apiError: 'Check that the MedReach API is running and try again.', breadcrumb: 'Breadcrumb', verified: 'Verified doctor', yearsExperience: '{{years}} years experience', independent: 'Independent practice', remote: 'Remote consultation', about: 'About', aboutDoctor: 'About {{name}}', details: 'Professional details', credentials: 'Credentials and practice', qualification: 'Qualification', experience: 'Experience', years: '{{years}} years', practice: 'Practice', location: 'Location', notListed: 'Not listed', verifiedBy: 'Verified by MedReach', verifiedCopy: 'Professional registration details were reviewed before this profile was made public.' },
    booking: { chooseNew: 'Choose a new time', book: 'Book a consultation', chooseDateTime: 'Choose a date and time', duration: '30 min', timezone: 'Available times are shown in Indian Standard Time.', chooseAppointmentDate: 'Choose an appointment date', today: 'Today', tomorrow: 'Tomorrow', available: 'available', unavailable: 'no availability', anotherDate: 'Another date', chooseAnotherDate: 'Choose another appointment date', availableTimes: 'Available times', oneSlot: '{{count}} slot', manySlots: '{{count}} slots', loadingSlots: 'Loading available slots', timesError: 'Available times could not be loaded.', noSlots: 'No slots on this date', noSlotsCopy: 'Choose another available date to continue.', fee: 'Consultation fee', shownAtConfirmation: 'Shown at confirmation', rescheduleTo: 'Reschedule to {{time}}', continueWith: 'Continue with {{time}}', selectTime: 'Select a time to continue', unchanged: 'Your current appointment stays unchanged until you confirm.', notCreated: 'No appointment is created until you confirm.', signInFirst: 'You’ll sign in before confirming the appointment.', selected: 'Selected consultation', reschedule: 'Reschedule consultation', confirmNew: 'Confirm your new time', confirm: 'Confirm appointment', patientRequired: 'Patient account required', signInContinue: 'Sign in to continue booking', closePrompt: 'Close booking prompt', date: 'Date', time: 'Time', confirmFee: 'Fee', currentStays: 'Your current appointment stays booked unless this new time is successfully reserved.', reservedAfter: 'Your appointment is reserved only after confirmation succeeds.', noPayment: 'No payment is taken now.', confirming: 'Confirming…', confirmNewTime: 'Confirm new time', slotTaken: 'This time was just taken or is no longer available. Choose another slot.', restricted: 'Doctor and Admin accounts cannot book appointments. Sign in with a Patient account to reserve a consultation.', signInCopy: 'Signing in protects your appointment information. This slot is not reserved until a Patient confirms it.', logIn: 'Log in', createPatient: 'Create patient account' },
    auth: { visualEyebrow: 'Continuous care, secure access', visualTitle: 'Care that continues.', visualCopy: 'Access your appointments and continue your care securely.', welcome: 'Welcome back', signInTitle: 'Sign in to MedReach', signInCopy: 'Access your appointments and continue your care.', waiting: 'Your appointment is waiting', waitingCopy: 'Your selected appointment will still be here after you sign in.', patientCreated: 'Your patient account was created. Sign in to continue.', email: 'Email', password: 'Password', show: 'Show', hide: 'Hide', signingIn: 'Signing in…', signIn: 'Sign in →', newUser: 'New to MedReach?', createAccount: 'Create an account →', fullName: 'Full name', confirmPassword: 'Confirm password', passwordHint: 'Use 12 to 128 characters.', join: 'Join MedReach', registerTitle: 'Create your account', registerCopy: 'Create a patient account to book consultations and continue your care.', creating: 'Creating account…', create: 'Create account →', already: 'Already have an account?', areDoctor: 'Are you a doctor?', joinLink: 'Join MedReach →', enterName: 'Enter your full name.', enterEmail: 'Enter your email address.', validEmail: 'Enter a valid email address.', enterPassword: 'Enter your password.', shortPassword: 'Use at least 12 characters.', longPassword: 'Password must be 128 characters or fewer.', confirmRequired: 'Confirm your password.', mismatch: 'Passwords do not match.', invalidCredentials: 'The email or password is incorrect. Please check both and try again.', disabled: 'This account is disabled. Please contact MedReach support for help.', review: 'Please check the information you entered and try again.', signInError: 'We could not sign you in right now. Please try again.', emailUsed: 'An account with this email already exists.', emailUsedCopy: 'This email is already registered. Try logging in instead.', validationReview: 'Please review the highlighted fields.', registerError: 'We could not create your account right now. Please try again.' },
    status: { booked: 'Booked', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No-show', rescheduled: 'Rescheduled', awaiting_outcome: 'Awaiting outcome' },
    appointments: { eyebrow: 'Your care schedule', title: 'My Appointments', copy: 'View upcoming consultations and review your previous appointment activity.', loading: 'Loading appointments', loadError: 'We couldn’t load your appointments', scheduledCare: 'Scheduled care', upcoming: 'Upcoming', appointment: 'appointment', appointments: 'appointments', upcomingConsultation: 'Upcoming consultation', scheduledConsultation: 'Scheduled consultation', remote: 'Remote consultation', viewAppointment: 'View appointment', viewDetails: 'View details', previous: 'Previous activity', history: 'History', record: 'record', records: 'records', noneUpcoming: 'No upcoming consultations', noneUpcomingCopy: 'When you’re ready, find a doctor and choose an available time.', findDoctor: 'Find a doctor', noneHistory: 'No previous appointment activity yet.', back: 'Back to appointments', loadingDetails: 'Loading appointment details', detailError: 'We couldn’t load this appointment', pastConsultation: 'Past consultation', viewDoctor: 'View doctor profile', yourConsultation: 'Your consultation', stateLabel: 'Current consultation status and actions', manage: 'Manage appointment', reschedule: 'Reschedule appointment', cancel: 'Cancel appointment', pastNote: 'This appointment is part of your previous care activity.', reference: 'Appointment reference: #{{id}}', historyTitle: 'Appointment history', previousActivity: 'Previous activity', cancelledAt: 'Cancelled {{date}}.', reason: 'Reason:', replaces: 'This booking replaces', replacedBy: 'This booking was replaced by', appointmentNumber: 'appointment #{{id}}' },
    cancellation: { eyebrow: 'Cancel appointment', sure: 'Are you sure?', patientCopy: 'The Doctor will be notified. If the slot remains active and in the future, another Patient may book it.', reason: 'Reason', optional: '(optional)', placeholder: 'Add a short note for the Doctor', keep: 'Keep appointment', cancelling: 'Cancelling…', cancel: 'Cancel appointment' },
    consultation: { loadingRecord: 'Loading consultation record…', recordError: 'We couldn’t load this consultation record. Please try again later.' },
    device: { checking: 'Checking…', available: 'Available', denied: 'Permission denied', unavailable: 'Not available', unsupported: 'Not supported', unsupportedCopy: 'Camera and microphone testing is not supported by this browser.', deniedCopy: 'Camera or microphone permission was denied. You can still continue and update browser permissions later.', preview: 'Camera preview', previewUnavailable: 'Camera preview unavailable', camera: 'Camera', microphone: 'Microphone', privacy: 'This check stays in your browser. MedReach does not upload or store camera or microphone data.', before: 'Before your consultation', title: 'Test camera & microphone', copy: 'Allow access to confirm that this device is ready. A successful test is helpful, but not required.', close: 'Close device check' },
    notifications: { booking: 'Booking', confirmed: 'Appointment confirmed', reschedule: 'Reschedule', rescheduled: 'Appointment rescheduled', cancellation: 'Cancellation', cancelled: 'Appointment cancelled', update: 'Update', appointmentUpdate: 'Appointment update', read: 'Read', unread: 'Unread', notification: '{{state}} notification: {{title}}', view: 'View appointment', marking: 'Marking…', markRead: 'Mark as read', today: 'Today', earlier: 'Earlier', eyebrow: 'Care updates', title: 'Notifications', copy: 'Important updates about your appointments and care.', unreadCount: '{{count}} unread', loading: 'Loading notifications', loadError: 'We couldn’t load notifications', empty: 'No updates yet', emptyCopy: 'Important appointment and account updates will appear here.', showing: 'Showing the newest {{pageSize}} of {{total}} notifications.' },
    record: { completed: 'Completed consultation', title: 'Consultation record', completedOn: 'Your consultation with {{name}} was completed on {{date}}.', notesEyebrow: 'Doctor’s notes', notesTitle: 'Doctor’s consultation notes', noNotes: 'No consultation notes were added.', prescription: 'Prescription', medicines: 'Medicines', noMedicines: 'No medicines were prescribed during this consultation.', medicine: 'Medicine {{number}}', dosage: 'Dosage', frequency: 'Frequency', duration: 'Duration', instructions: 'Instructions', followUp: 'Follow-up', recommended: 'Follow-up recommended', followIn: 'Follow up in {{interval}} {{unit}}.', around: 'Recommended around', viewAvailability: 'View doctor availability', chooseAny: 'You can choose any normally available appointment time.', noFollowUp: 'No follow-up recommended', noFollowUpCopy: 'No follow-up was recommended for this consultation.', unitDay: 'day', unitDays: 'days', unitWeek: 'week', unitWeeks: 'weeks', unitMonth: 'month', unitMonths: 'months' },
    protection: { checking: 'Checking your MedReach session…', sessionTitle: 'We couldn’t confirm your session', sessionCopy: 'The MedReach server may be temporarily unavailable. Try again before continuing.', roleEyebrow: 'Role-protected area', roleTitle: 'This page isn’t available for your account', roleCopy: 'MedReach keeps Patient and Doctor appointment tools separate.', goAppointments: 'Go to your appointments' },
    notFound: { title: 'This page is not ready yet', copy: 'Return home while we finish the next part of doctor discovery.', back: 'Back to home' },
  },
  hi: {
    language: { label: 'भाषा', english: 'English', hindi: 'हिंदी' },
    navigation: {
      primary: 'मुख्य नेविगेशन', account: 'अकाउंट नेविगेशन', findDoctors: 'डॉक्टर खोजें', myAppointments: 'मेरी बुकिंग्स', appointments: 'बुकिंग्स', notifications: 'नोटिफिकेशन',
      login: 'लॉग इन', register: 'अकाउंट बनाएँ', logout: 'लॉग आउट', wait: 'रुकें…', greeting: 'नमस्ते,', checkingSession: 'लॉग इन की जानकारी देखी जा रही है',
      notificationCount: '{{count}} नए नोटिफिकेशन', logoutFailed: 'लॉग आउट नहीं हो पाया। फिर से कोशिश करें।',
    },
    common: { tryAgain: 'फिर से कोशिश करें', home: 'होम', medreachHome: 'MedReach होम', patientConsultationActions: 'मरीज के कंसल्टेशन के विकल्प', doctors: 'डॉक्टर', close: 'बंद करें', previous: 'पिछला', next: 'अगला' },
    footer: { patients: 'मरीजों के लिए', forDoctors: 'डॉक्टरों के लिए', howItWorks: 'कैसे काम करता है', doctorLogin: 'डॉक्टर लॉग इन', verification: 'वेरिफिकेशन', about: 'हमारे बारे में', privacy: 'प्राइवेसी', terms: 'नियम', description: 'ऑनलाइन डॉक्टर खोजें, बुकिंग करें और देखभाल जारी रखें।', findDoctor: 'डॉक्टर खोजें', rights: '© 2026 MedReach. सभी अधिकार सुरक्षित।', emergency: 'MedReach इमरजेंसी सेवा नहीं है। तुरंत मदद के लिए स्थानीय इमरजेंसी सेवा से संपर्क करें।', label: 'फुटर' },
    search: { label: 'डॉक्टर खोजें', placeholder: 'डॉक्टर, स्पेशलाइजेशन या स्वास्थ्य समस्या खोजें', submit: 'डॉक्टर खोजें' },
    home: {
      heroEyebrow: 'ऑनलाइन देखभाल, आसान तरीके से', heroTitle: 'जहाँ भी हों, डॉक्टर से जुड़े रहें।', heroCopy: 'वेरिफाइड डॉक्टर खोजें, खाली समय देखें और ऑनलाइन डॉक्टर से बात करें।', heroAlt: 'अपने कंसल्टेशन रूम से ऑनलाइन देखभाल देती डॉक्टर', emergency: 'यह इमरजेंसी सेवा नहीं है। तुरंत मदद के लिए अपनी स्थानीय इमरजेंसी सेवा से संपर्क करें।',
      browse: 'देखभाल खोजें', browseTitle: 'अपनी जरूरत के हिसाब से डॉक्टर चुनें।', browseCopy: 'अपनी समस्या चुनें और सही स्पेशलिटी के डॉक्टर देखें।', viewAll: 'सभी डॉक्टर देखें', loadingSpecializations: 'स्पेशलिटी लोड हो रही हैं', specializationError: 'स्पेशलिटी की जानकारी अभी नहीं मिल रही। आप फिर भी डॉक्टर खोज सकते हैं।',
      journey: 'आपकी देखभाल का सफर', journeyTitle: 'देखभाल के चार आसान कदम।', journeyCopy: 'डॉक्टर खोजें, समय चुनें, ऑनलाइन बात करें और जरूरत हो तो फॉलो-अप करें।', stepSearch: 'डॉक्टर खोजें', stepSearchCopy: 'समस्या या स्पेशलिटी से डॉक्टर खोजें।', stepChoose: 'समय चुनें', stepChooseCopy: 'डॉक्टर का खाली समय चुनें।', stepMeet: 'ऑनलाइन बात करें', stepMeetCopy: 'डॉक्टर से ऑनलाइन जुड़ें।', stepContinue: 'फॉलो-अप करें', stepContinueCopy: 'डॉक्टर की सलाह के अनुसार देखभाल जारी रखें।',
      continuity: 'देखभाल जुड़ी रहे', continuityTitle: 'पिछली देखभाल साथ रहे।', continuityCopy: 'डॉक्टर की पिछली सलाह और फॉलो-अप से आगे की देखभाल आसान रहती है।', createAccount: 'अकाउंट बनाएँ', continuityAlt: 'घर पर अपना फॉलो-अप प्लान देखती मरीज',
      discovery: 'डॉक्टर की जानकारी', discoveryTitle: 'बुक करने से पहले डॉक्टर को जानें।', discoveryCopy: 'प्रोफाइल, योग्यता, अनुभव और स्पेशलिटी देखें, फिर समय चुनें।', discoveryAlt: 'ऑनलाइन कंसल्टेशन में ध्यान से बात करती डॉक्टर',
      beyond: 'जरूरी जानकारी', beyondTitle: 'स्वास्थ्य की जरूरी जानकारी, एक जगह।', beyondCopy: 'दवाइयों और सेहत से जुड़ी आसान जानकारी देखें।', medicines: 'दवाइयाँ', medicinesTitle: 'दवाइयों की जानकारी', medicinesCopy: 'प्रिस्क्रिप्शन से जुड़ी दवाइयों को आसानी से समझें।', medicinesAlt: 'देखभाल की जानकारी के साथ रखी प्रिस्क्रिप्शन दवाइयाँ', doctorInsights: 'डॉक्टर की सलाह', insightsTitle: 'डॉक्टर की सलाह', insightsCopy: 'वेरिफाइड डॉक्टरों से उपयोगी जानकारी।', insightsAlt: 'हेल्थ जानकारी पढ़ती डॉक्टर', meetDoctors: 'डॉक्टर खोजें', healthArticles: 'हेल्थ आर्टिकल', articlesTitle: 'हेल्थ आर्टिकल', articlesCopy: 'आसान भाषा में भरोसेमंद हेल्थ जानकारी।',
      trust: 'हर कदम पर भरोसा', trustTitle: 'भरोसे के साथ देखभाल।', trustOne: 'डॉक्टर की जाँच', trustOneCopy: 'प्रोफाइल दिखाने से पहले डॉक्टर की जानकारी जाँची जाती है।', trustTwo: 'आपकी प्राइवेसी', trustTwoCopy: 'आपकी हेल्थ जानकारी सही अनुमति से ही देखी जा सकती है।', trustThree: 'जुड़ी हुई देखभाल', trustThreeCopy: 'बुकिंग, डॉक्टर की सलाह और फॉलो-अप एक जगह जुड़े रहते हैं।',
    },
    specializations: { 'General Medicine': 'जनरल मेडिसिन', Dermatology: 'त्वचा रोग', Cardiology: 'दिल के रोग', Gynecology: 'महिला स्वास्थ्य', Pediatrics: 'बच्चों के डॉक्टर', Psychiatry: 'मानसिक स्वास्थ्य' },
    filters: { label: 'डॉक्टर फ़िल्टर', specialization: 'डॉक्टर की स्पेशलिटी', specializationFilter: 'स्पेशलिटी फ़िल्टर', allSpecializations: 'सभी स्पेशलिटी', availability: 'तारीख फ़िल्टर', fee: 'फीस', feeFilter: 'फीस फ़िल्टर', experience: 'अनुभव', experienceFilter: 'अनुभव फ़िल्टर', all: 'फ़िल्टर', clearAll: 'सब हटाएँ', refine: 'खोज बदलें', allFilters: 'सभी फ़िल्टर', close: 'सभी फ़िल्टर बंद करें', availableOn: 'तारीख', consultationFee: 'डॉक्टर की फीस', anyFee: 'कोई भी फीस', upTo: '₹{{amount}} तक', anyExperience: 'कोई भी अनुभव', yearsPlus: '{{years}}+ साल', reset: 'फ़िल्टर हटाएँ', showResults: 'नतीजे देखें' },
    calendar: { anyDate: 'कोई भी तारीख', chooseDate: 'उपलब्ध तारीख चुनें', previousMonth: 'पिछला महीना', nextMonth: 'अगला महीना', clear: 'हटाएँ', today: 'आज', weekdays: ['र', 'सो', 'मं', 'बु', 'गु', 'शु', 'श'] },
    results: { breadcrumb: 'पेज का रास्ता', findCare: 'डॉक्टर खोजें', title: 'डॉक्टर खोजें', copy: 'डॉक्टर की स्पेशलिटी, जानकारी और खाली समय देखकर सही डॉक्टर खोजें।', specializationError: 'स्पेशलिटी के विकल्प अभी नहीं मिल रहे।', finding: 'डॉक्टर खोजे जा रहे हैं…', oneFound: '{{count}} डॉक्टर मिला', manyFound: '{{count}} डॉक्टर मिले', forQuery: 'खोज के नतीजे', sort: 'क्रम:', earliest: 'जल्दी उपलब्ध डॉक्टर पहले', loadError: 'डॉक्टर लोड नहीं हो पाए', noMatch: 'कोई डॉक्टर नहीं मिला', noMatchCopy: 'अपनी खोज या फ़िल्टर बदलकर देखें।', clearFilters: 'फ़िल्टर हटाएँ', pagination: 'डॉक्टर नतीजों के पेज', page: 'पेज {{page}} / {{pages}}' },
    doctorCard: { portrait: '{{name}} की फोटो', verified: 'वेरिफाइड डॉक्टर', yearsExperience: '{{years}} साल का अनुभव', selectedDate: 'चुनी हुई तारीख', nextAvailable: 'अगला खाली समय', available: '{{date}} को उपलब्ध', noSlots: 'अभी कोई स्लॉट नहीं', consultationFee: 'डॉक्टर की फीस', viewProfile: 'डॉक्टर की प्रोफाइल देखें' },
    profile: { notFound: 'डॉक्टर की प्रोफाइल नहीं मिली', loadError: 'यह प्रोफाइल लोड नहीं हो पाई', unavailable: 'यह डॉक्टर अभी उपलब्ध नहीं है या प्रोफाइल अब सार्वजनिक नहीं है।', apiError: 'MedReach सर्वर की जाँच करें और फिर से कोशिश करें।', breadcrumb: 'पेज का रास्ता', verified: 'वेरिफाइड डॉक्टर', yearsExperience: '{{years}} साल का अनुभव', independent: 'अपनी प्रैक्टिस', remote: 'ऑनलाइन डॉक्टर से बात', about: 'जानकारी', aboutDoctor: '{{name}} के बारे में', details: 'डॉक्टर की जानकारी', credentials: 'योग्यता और अनुभव', qualification: 'योग्यता', experience: 'अनुभव', years: '{{years}} साल', practice: 'क्लिनिक', location: 'जगह', notListed: 'जानकारी नहीं दी गई', verifiedBy: 'MedReach से वेरिफाइड', verifiedCopy: 'यह प्रोफाइल दिखाने से पहले डॉक्टर के रजिस्ट्रेशन की जानकारी जाँची गई।' },
    booking: { chooseNew: 'नया समय चुनें', book: 'बुकिंग करें', chooseDateTime: 'तारीख और समय चुनें', duration: '30 मिनट', timezone: 'समय भारतीय समय के अनुसार दिखाया गया है।', chooseAppointmentDate: 'बुकिंग की तारीख चुनें', today: 'आज', tomorrow: 'कल', available: 'उपलब्ध', unavailable: 'उपलब्ध नहीं', anotherDate: 'दूसरी तारीख', chooseAnotherDate: 'दूसरी तारीख चुनें', availableTimes: 'खाली समय', oneSlot: '{{count}} स्लॉट', manySlots: '{{count}} स्लॉट', loadingSlots: 'खाली समय लोड हो रहा है', timesError: 'खाली समय लोड नहीं हो पाया।', noSlots: 'इस दिन कोई समय खाली नहीं है।', noSlotsCopy: 'दूसरी तारीख चुनें।', fee: 'डॉक्टर की फीस', shownAtConfirmation: 'पक्का करते समय दिखेगी', rescheduleTo: '{{time}} चुनें', continueWith: '{{time}} चुनें', selectTime: 'पहले समय चुनें', unchanged: 'पक्का करने तक आपकी मौजूदा बुकिंग बनी रहेगी।', notCreated: 'पक्का करने तक बुकिंग नहीं बनेगी।', signInFirst: 'बुकिंग पक्की करने से पहले लॉग इन करें।', selected: 'चुनी हुई बुकिंग', reschedule: 'समय बदलें', confirmNew: 'नया समय पक्का करें', confirm: 'बुकिंग पक्की करें', patientRequired: 'मरीज का अकाउंट जरूरी है', signInContinue: 'बुकिंग जारी रखने के लिए लॉग इन करें', closePrompt: 'बुकिंग विंडो बंद करें', date: 'तारीख', time: 'समय', confirmFee: 'फीस', currentStays: 'नया समय पक्का होने तक आपकी मौजूदा बुकिंग बनी रहेगी।', reservedAfter: 'पक्की करने के बाद यह समय आपके लिए बुक हो जाएगा।', noPayment: 'अभी कोई पेमेंट नहीं लिया जाएगा।', confirming: 'पक्का हो रहा है…', confirmNewTime: 'नया समय पक्का करें', slotTaken: 'यह समय अभी किसी और ने ले लिया है या अब उपलब्ध नहीं है। दूसरा समय चुनें।', restricted: 'डॉक्टर और एडमिन अकाउंट से बुकिंग नहीं की जा सकती। मरीज के अकाउंट से लॉग इन करें।', signInCopy: 'लॉग इन करने पर आपकी बुकिंग की जानकारी सुरक्षित रहती है। बुकिंग पक्की होने तक समय रिजर्व नहीं होगा।', logIn: 'लॉग इन', createPatient: 'मरीज का अकाउंट बनाएँ' },
    auth: { visualEyebrow: 'जुड़ी हुई देखभाल, सुरक्षित लॉग इन', visualTitle: 'देखभाल जारी रहे।', visualCopy: 'अपनी बुकिंग्स देखें और देखभाल सुरक्षित तरीके से जारी रखें।', welcome: 'स्वागत है', signInTitle: 'MedReach में लॉग इन करें', signInCopy: 'अपनी बुकिंग्स देखें और देखभाल जारी रखें।', waiting: 'आपकी बुकिंग तैयार है', waitingCopy: 'लॉग इन करने के बाद भी आपकी चुनी हुई बुकिंग यहीं रहेगी।', patientCreated: 'आपका मरीज अकाउंट बन गया है। जारी रखने के लिए लॉग इन करें।', email: 'ईमेल', password: 'पासवर्ड', show: 'दिखाएँ', hide: 'छिपाएँ', signingIn: 'लॉग इन हो रहा है…', signIn: 'लॉग इन →', newUser: 'MedReach पर नए हैं?', createAccount: 'अकाउंट बनाएँ →', fullName: 'पूरा नाम', confirmPassword: 'पासवर्ड फिर से डालें', passwordHint: '12 से 128 अक्षर इस्तेमाल करें।', join: 'अकाउंट बनाएँ', registerTitle: 'अपना अकाउंट बनाएँ', registerCopy: 'डॉक्टर से बात करने के लिए बुकिंग करें और अपनी देखभाल जारी रखें।', creating: 'अकाउंट बन रहा है…', create: 'अकाउंट बनाएँ →', already: 'पहले से अकाउंट है?', areDoctor: 'क्या आप डॉक्टर हैं?', joinLink: 'MedReach से जुड़ें →', enterName: 'अपना पूरा नाम लिखें।', enterEmail: 'अपना ईमेल लिखें।', validEmail: 'सही ईमेल लिखें।', enterPassword: 'अपना पासवर्ड लिखें।', shortPassword: 'कम से कम 12 अक्षर इस्तेमाल करें।', longPassword: 'पासवर्ड 128 अक्षर या उससे कम होना चाहिए।', confirmRequired: 'पासवर्ड फिर से डालें।', mismatch: 'दोनों पासवर्ड एक जैसे नहीं हैं।', invalidCredentials: 'ईमेल या पासवर्ड सही नहीं है। दोनों जाँचकर फिर कोशिश करें।', disabled: 'यह अकाउंट बंद है। मदद के लिए MedReach सपोर्ट से संपर्क करें।', review: 'लिखी हुई जानकारी जाँचकर फिर कोशिश करें।', signInError: 'अभी लॉग इन नहीं हो पाया। फिर से कोशिश करें।', emailUsed: 'इस ईमेल से अकाउंट पहले से बना हुआ है।', emailUsedCopy: 'यह ईमेल पहले से रजिस्टर है। लॉग इन करके देखें।', validationReview: 'दिखाए गए फील्ड जाँचें।', registerError: 'अभी अकाउंट नहीं बन पाया। फिर से कोशिश करें।' },
    status: { booked: 'बुकिंग पक्की', completed: 'पूरा हुआ', cancelled: 'कैंसल', no_show: 'मुलाकात नहीं हुई', rescheduled: 'समय बदला', awaiting_outcome: 'डॉक्टर की कार्रवाई बाकी' },
    appointments: { eyebrow: 'आपकी बुकिंग्स', title: 'मेरी बुकिंग्स', copy: 'आने वाली और पिछली बुकिंग्स देखें।', loading: 'बुकिंग्स लोड हो रही हैं…', loadError: 'बुकिंग्स लोड नहीं हो पाईं', scheduledCare: 'आने वाली', upcoming: 'आने वाली बुकिंग्स', appointment: 'बुकिंग', appointments: 'बुकिंग्स', upcomingConsultation: 'आने वाली बुकिंग', scheduledConsultation: 'आने वाली बुकिंग', remote: 'ऑनलाइन डॉक्टर से बात', viewAppointment: 'बुकिंग देखें', viewDetails: 'बुकिंग देखें', previous: 'पिछली', history: 'पिछली बुकिंग्स', record: 'बुकिंग', records: 'बुकिंग्स', noneUpcoming: 'अभी कोई बुकिंग नहीं है।', noneUpcomingCopy: 'डॉक्टर खोजें और अपनी सुविधा का समय चुनें।', findDoctor: 'डॉक्टर खोजें', noneHistory: 'अभी कोई पिछली बुकिंग नहीं है।', back: 'बुकिंग्स पर वापस जाएँ', loadingDetails: 'बुकिंग की जानकारी लोड हो रही है…', detailError: 'बुकिंग लोड नहीं हो पाई', pastConsultation: 'पिछली बुकिंग', viewDoctor: 'डॉक्टर की प्रोफाइल देखें', yourConsultation: 'ऑनलाइन डॉक्टर से बात', stateLabel: 'बुकिंग की स्थिति और विकल्प', manage: 'बुकिंग बदलें या कैंसल करें', reschedule: 'समय बदलें', cancel: 'बुकिंग कैंसल करें', pastNote: 'यह आपकी पिछली बुकिंग है।', reference: 'बुकिंग नंबर: #{{id}}', historyTitle: 'बुकिंग की जानकारी', previousActivity: 'पिछली जानकारी', cancelledAt: '{{date}} को कैंसल किया गया।', reason: 'कारण:', replaces: 'यह बुकिंग इसकी जगह है', replacedBy: 'इस बुकिंग की जगह नई बुकिंग बनी', appointmentNumber: 'बुकिंग #{{id}}' },
    cancellation: { eyebrow: 'बुकिंग कैंसल करें', sure: 'क्या आप यह बुकिंग कैंसल करना चाहते हैं?', patientCopy: 'डॉक्टर को नोटिफिकेशन मिलेगा। जरूरत हो तो आप दूसरा समय बुक कर सकते हैं।', reason: 'कारण', optional: '(जरूरी नहीं)', placeholder: 'डॉक्टर के लिए छोटा नोट लिखें', keep: 'बुकिंग रखें', cancelling: 'कैंसल हो रही है…', cancel: 'बुकिंग कैंसल करें' },
    consultation: { loadingRecord: 'डॉक्टर से हुई बातचीत का रिकॉर्ड लोड हो रहा है…', recordError: 'रिकॉर्ड लोड नहीं हो पाया। बाद में फिर कोशिश करें।' },
    device: { checking: 'जाँच हो रही है…', available: 'उपलब्ध', denied: 'इजाजत नहीं मिली', unavailable: 'उपलब्ध नहीं', unsupported: 'सपोर्ट नहीं करता', unsupportedCopy: 'यह ब्राउज़र कैमरा और माइक्रोफोन टेस्ट सपोर्ट नहीं करता।', deniedCopy: 'कैमरा या माइक्रोफोन की इजाजत नहीं मिली। आप फिर भी जारी रख सकते हैं और बाद में ब्राउज़र की परमिशन बदल सकते हैं।', preview: 'कैमरा प्रीव्यू', previewUnavailable: 'कैमरा प्रीव्यू उपलब्ध नहीं', camera: 'कैमरा', microphone: 'माइक्रोफोन', privacy: 'यह जाँच आपके ब्राउज़र में ही होती है। MedReach कैमरा या माइक्रोफोन का डेटा अपलोड या सेव नहीं करता।', before: 'कंसल्टेशन से पहले', title: 'कैमरा और माइक्रोफोन टेस्ट करें', copy: 'इस डिवाइस की जाँच के लिए इजाजत दें। टेस्ट सफल होना मददगार है, लेकिन जरूरी नहीं।', close: 'डिवाइस टेस्ट बंद करें' },
    notifications: { booking: 'बुकिंग', confirmed: 'बुकिंग पक्की हुई', reschedule: 'समय बदला', rescheduled: 'बुकिंग का समय बदला', cancellation: 'कैंसल', cancelled: 'बुकिंग कैंसल हुई', update: 'अपडेट', appointmentUpdate: 'बुकिंग अपडेट', read: 'पढ़ा हुआ', unread: 'नया', notification: '{{state}} नोटिफिकेशन: {{title}}', view: 'बुकिंग देखें', marking: 'अपडेट हो रहा है…', markRead: 'पढ़ा हुआ मार्क करें', today: 'आज', earlier: 'पुराने', eyebrow: 'आपके अपडेट', title: 'नोटिफिकेशन', copy: 'आपकी बुकिंग और देखभाल से जुड़े अपडेट।', unreadCount: '{{count}} नए', loading: 'नोटिफिकेशन लोड हो रहे हैं…', loadError: 'नोटिफिकेशन लोड नहीं हो पाए', empty: 'अभी कोई नया नोटिफिकेशन नहीं है।', emptyCopy: 'बुकिंग और अकाउंट के अपडेट यहाँ दिखेंगे।', showing: 'सबसे नए {{pageSize}} नोटिफिकेशन दिख रहे हैं, कुल {{total}}।' },
    record: { completed: 'पूरा हुआ', title: 'कंसल्टेशन रिकॉर्ड', completedOn: '{{name}} से कंसल्टेशन {{date}} पूरा हुआ।', notesEyebrow: 'नोट्स', notesTitle: 'डॉक्टर के नोट्स', noNotes: 'डॉक्टर ने कोई नोट नहीं जोड़ा।', prescription: 'प्रिस्क्रिप्शन', medicines: 'दवाइयाँ', noMedicines: 'कोई दवा नहीं लिखी गई।', medicine: 'दवा {{number}}', dosage: 'खुराक', frequency: 'कितनी बार', duration: 'कितने दिन', instructions: 'कैसे लें', followUp: 'फॉलो-अप', recommended: 'फॉलो-अप की सलाह', followIn: '{{interval}} {{unit}} में फॉलो-अप करें।', around: 'फॉलो-अप की तारीख:', viewAvailability: 'डॉक्टर का खाली समय देखें', chooseAny: 'आप कोई भी उपलब्ध समय चुन सकते हैं।', noFollowUp: 'फॉलो-अप की सलाह नहीं', noFollowUpCopy: 'डॉक्टर ने फॉलो-अप की सलाह नहीं दी।', unitDay: 'दिन', unitDays: 'दिन', unitWeek: 'हफ्ता', unitWeeks: 'हफ्ते', unitMonth: 'महीना', unitMonths: 'महीने' },
    protection: { checking: 'आपका MedReach सेशन जाँचा जा रहा है…', sessionTitle: 'लॉग इन की जानकारी नहीं मिल पाई', sessionCopy: 'MedReach सर्वर अभी उपलब्ध नहीं हो सकता। फिर कोशिश करें।', roleEyebrow: 'यह हिस्सा इस अकाउंट के लिए नहीं है', roleTitle: 'यह पेज आपके अकाउंट पर उपलब्ध नहीं है', roleCopy: 'MedReach मरीज और डॉक्टर के बुकिंग टूल अलग रखता है।', goAppointments: 'अपनी बुकिंग्स पर जाएँ' },
    notFound: { title: 'यह पेज अभी तैयार नहीं है', copy: 'होम पर वापस जाएँ।', back: 'होम पर वापस जाएँ' },
  },
}

function lookup(language, key) {
  return key.split('.').reduce((value, part) => value?.[part], messages[language])
}

export function translateMessage(language, key, values = {}) {
  const template = lookup(language, key) ?? lookup('en', key) ?? key
  return String(template).replace(/\{\{(\w+)\}\}/gu, (_, name) => String(values[name] ?? ''))
}

export function specializationDisplayName(language, name) {
  return messages[language]?.specializations?.[name] ?? name
}
